name = "websocket-server"
main = "./src/index.mjs"
compatibility_date = "2022-09-08"
compatibility_flags = [ "nodejs_compat" ]

[[durable_objects.bindings]]
name = "WEBSOCKET_SERVER"
class_name = "WebSocketServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketServer"]